# Generated by Django 5.0.2 on 2024-04-18 12:36

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberObject', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='expiry_date',
            field=models.DateTimeField(default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=30))), editable=False),
        ),
    ]
